name: KING13 APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать проект
        uses: actions/checkout@v4

      - name: Установить Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Собрать APK
        run: ./gradlew assembleDebug

      - name: Загрузить APK
        uses: actions/upload-artifact@v4
        with:
          name: KING13-APK
          path: app/build/outputs/apk/debug/app-debug.apk
